<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCaqbdcm\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCaqbdcm/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCaqbdcm.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCaqbdcm\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCaqbdcm\appProdProjectContainer([
    'container.build_hash' => 'Caqbdcm',
    'container.build_id' => '427d3d77',
    'container.build_time' => 1706473885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCaqbdcm');
