<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9zulxc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9zulxc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE9zulxc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE9zulxc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE9zulxc\appProdProjectContainer([
    'container.build_hash' => 'E9zulxc',
    'container.build_id' => '8f5383a4',
    'container.build_time' => 1706477418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9zulxc');
